### PR TITLE
Initial request

### PR DESCRIPTION
**Pull request by tshavor**

### CODE REVIEW

**Comment by brendalong** [comment]
You are close.
Clean up the indentation in the html code, this will make it easier to read and de-bug.

Run your page through the w3 validator - https://validator.w3.org/
This will help you with many errors in the code which could be causing display issues. 

Check out the bootstrap styling for the columns. Remember the numbers will always add up to 12. You should only have three of these: class="col-md-4".
http://getbootstrap.com/examples/grid/

Remove the current content when you display new - you are calling $("#output").empty(); - however it is missing from your html.

Switch the buttons to a dropdown.

**Comment by tshavor** [comment]
Thank you!

Thomas

**Comment by brendalong** [comment]
Yes, I did get this. I guess it took a moment.

**Comment by brendalong** [comment]
Line 1 - console.log typo

Great, your dropdown is now working and you are clearing and displaying the categories.

loadFireworks/loadDestructives
When building the display using bootstrap. You need to identify rows and within each row, the columns should equal 12.

Currently, you are missing the row <div class="row">
and when you add the columns, it equals more than 12. This causes the layout to display wrong (especially on smaller screens).

You could set a variable based on modulus and if true, include the opening div, and closing div. 

When you turn in a project, only keep comments related to your specific code - all the extra at the bottom is not necessary to run this file. I understand you may want to keep the reference, consider keeping it in another file.

**Pull request closed without merging**
